apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 10-postgres-service.yaml
  - 20-postgres-statefulset.yaml
  - 30-app-deployment.yaml
  - 40-app-service.yaml
  - 50-network-policy.yaml
configMapGenerator:
  - name: postgres-init-app-role
    namespace: tenant-saas
    files:
      - 10-app-role.sh=postgres/10-app-role.sh
generatorOptions:
  disableNameSuffixHash: true
